import sys


def get_symbols_for(
    symbol_group, lang_to, lang_from="asciimath"
):  # pragma: no cover
    return {
        i[lang_from]: (i[lang_to] if lang_to is not None else None)
        for i in getattr(sys.modules[__name__], symbol_group)
    }


binary_functions = [
    {"asciimath": "frac", "latex": "\\frac", "mathml": "<mfrac>{}{}</mfrac>"},
    {"asciimath": "root", "latex": "\\sqrt", "mathml": "<mroot>{}{}</mroot>"},
    {
        "asciimath": "stackrel",
        "latex": "\\stackrel",
        "mathml": "<mover>{}{}</mover>",
    },
    {
        "asciimath": "overset",
        "latex": "\\overset",
        "mathml": "<mover>{}{}</mover>",
    },
    {
        "asciimath": "underset",
        "latex": "\\underset",
        "mathml": "<munder>{}{}</munder>",
    },
    {
        "asciimath": "color",
        "latex": "\\textcolor",
        "mathml": "<mstyle mathcolor='{}'>{}</mstyle>",
    },
]

unary_functions = [
    {"asciimath": "sqrt", "latex": "\\sqrt", "mathml": "<msqrt>{}</msqrt>"},
    {"asciimath": "text", "latex": "\\textrm", "mathml": "<mtext>{}</mtext>"},
    {"asciimath": "abs", "latex": "abs", "mathml": "<mo>|</mo>{}<mo>|</mo>"},
    {
        "asciimath": "floor",
        "latex": "floor",
        "mathml": "<mo>&lfloor;</mo>{}<mo>&rfloor;</mo>",
    },
    {
        "asciimath": "ceil",
        "latex": "ceil",
        "mathml": "<mo>&lceil;</mo>{}<mo>&rceil;</mo>",
    },
    {
        "asciimath": "norm",
        "latex": "norm",
        "mathml": "<mo>&DoubleVerticalBar;</mo>{}<mo>&DoubleVerticalBar;</mo>",
    },
    {
        "asciimath": "ubrace",
        "latex": "\\underbrace",
        "mathml": "<munder>{}<mo>&#x23DF;</mo></munder>",
    },
    {
        "asciimath": "underbrace",
        "latex": "\\underbrace",
        "mathml": "<munder>{}<mo>&#x23DF;</mo></munder>",
    },
    {
        "asciimath": "obrace",
        "latex": "\\overbrace",
        "mathml": "<mover>{}<mo>&#x23DF;</mo></mover>",
    },
    {
        "asciimath": "overbrace",
        "latex": "\\overbrace",
        "mathml": "<mover>{}<mo>&#x23DF;</mo></mover>",
    },
    {
        "asciimath": "cancel",
        "latex": "\\cancel",
        "mathml": "<menclose notation='updiagonalstrike'>{}</menclose>",
    },
    {
        "asciimath": "bb",
        "latex": "\\boldsymbol",
        "mathml": "<mstyle mathvariant='bold'>{}</mstyle>",
    },
    {
        "asciimath": "bbb",
        "latex": "\\mathbb",
        "mathml": "<mstyle mathvariant='double-struck'>{}</mstyle>",
    },
    {
        "asciimath": "cc",
        "latex": "\\mathcal",
        "mathml": "<mstyle mathvariant='script'>{}</mstyle>",
    },
    {
        "asciimath": "tt",
        "latex": "\\texttt",
        "mathml": "<mstyle mathvariant='monospace'>{}</mstyle>",
    },
    {
        "asciimath": "fr",
        "latex": "\\mathfrak",
        "mathml": "<mstyle mathvariant='fraktur'>{}</mstyle>",
    },
    {
        "asciimath": "sf",
        "latex": "\\textsf",
        "mathml": "<mstyle mathvariant='sanf-serif'>{}</mstyle>",
    },
    {
        "asciimath": "ul",
        "latex": "\\underline",
        "mathml": "<munder>{}<mo>&#x332;</mo></munder>",
    },
    {
        "asciimath": "underline",
        "latex": "\\underline",
        "mathml": "<munder>{}<mo>&#x332;</mo></munder>",
    },
    {
        "asciimath": "bar",
        "latex": "\\overline",
        "mathml": "<mover>{}<mo>&#x332;</mo></mover>",
    },
    {
        "asciimath": "overline",
        "latex": "\\overline",
        "mathml": "<mover>{}<mo>&#x332;</mo></mover>",
    },
    {
        "asciimath": "hat",
        "latex": "\\hat",
        "mathml": "<mover>{}<mo>^</mo></mover>",
    },
    {
        "asciimath": "vec",
        "latex": "\\vec",
        "mathml": "<mover>{}<mo stretchy='false'>&#x2192;</mo></mover>",
    },
    {
        "asciimath": "dot",
        "latex": "\\dot",
        "mathml": "<mover>{}<mo stretchy='false'>.</mo></mover>",
    },
    {
        "asciimath": "ddot",
        "latex": "\\ddot",
        "mathml": "<mover>{}<mo stretchy='false'>..</mo></mover>",
    },
    {
        "asciimath": "dstyle",
        "latex": "\\displaystyle",
        "mathml": "<mstyle displaystyle='true'>{}</mstyle>",
    },
]

operation_symbols = [
    {"asciimath": "+", "latex": "+", "mathml": "+"},
    {"asciimath": "*", "latex": "\\cdot", "mathml": "&sdot;"},
    {"asciimath": "-", "latex": "-", "mathml": "-"},
    {"asciimath": "cdot", "latex": "\\cdot", "mathml": "&sdot;"},
    {"asciimath": "**", "latex": "\\ast", "mathml": "&ast;"},
    {"asciimath": "ast", "latex": "\\ast", "mathml": "&ast;"},
    {"asciimath": "***", "latex": "\\star", "mathml": "&Star;"},
    {"asciimath": "star", "latex": "\\star", "mathml": "&Star;"},
    {"asciimath": "//", "latex": "/", "mathml": "/"},
    {"asciimath": r"\\", "latex": "\\setminus", "mathml": "&setminus;"},
    {"asciimath": "setminus", "latex": "\\setminus", "mathml": "&setminus;"},
    {"asciimath": "xx", "latex": "\\times", "mathml": "&times;"},
    {"asciimath": "times", "latex": "\\times", "mathml": "&times;"},
    {"asciimath": "-:", "latex": "\\div", "mathml": "&div;"},
    {"asciimath": "div", "latex": "\\div", "mathml": "&div;"},
    {"asciimath": "|><", "latex": "\\ltimes", "mathml": "&ltimes;"},
    {"asciimath": "ltimes", "latex": "\\ltimes", "mathml": "&ltimes;"},
    {"asciimath": "><|", "latex": "\\rtimes", "mathml": "&rtimes;"},
    {"asciimath": "rtimes", "latex": "\\rtimes", "mathml": "&rtimes;"},
    {"asciimath": "|><|", "latex": "\\bowtie", "mathml": "&bowtie;"},
    {"asciimath": "bowtie", "latex": "\\bowtie", "mathml": "&bowtie;"},
    {"asciimath": "@", "latex": "\\circ", "mathml": "&SmallCircle;"},
    {"asciimath": "circ", "latex": "\\circ", "mathml": "&SmallCircle;"},
    {"asciimath": "o+", "latex": "\\oplus", "mathml": "&oplus;"},
    {"asciimath": "oplus", "latex": "\\oplus", "mathml": "&oplus;"},
    {"asciimath": "ox", "latex": "\\otimes", "mathml": "&times;"},
    {"asciimath": "otimes", "latex": "\\otimes", "mathml": "&times;"},
    {"asciimath": "o.", "latex": "\\odot", "mathml": "&odot;"},
    {"asciimath": "odot", "latex": "\\odot", "mathml": "&odot;"},
    {"asciimath": "sum", "latex": "\\sum", "mathml": "&sum;"},
    {"asciimath": "prod", "latex": "\\prod", "mathml": "&prod;"},
    {"asciimath": "^^", "latex": "\\wedge", "mathml": "&wedge;"},
    {"asciimath": "wedge", "latex": "\\wedge", "mathml": "&wedge;"},
    {"asciimath": "^^^", "latex": "\\bigwedge", "mathml": "&bigwedge;"},
    {"asciimath": "bigwedge", "latex": "\\bigwedge", "mathml": "&bigwedge;"},
    {"asciimath": "vv", "latex": "\\vee", "mathml": "&vee;"},
    {"asciimath": "vee", "latex": "\\vee", "mathml": "&vee;"},
    {"asciimath": "vvv", "latex": "\\bigvee", "mathml": "&bigvee;"},
    {"asciimath": "bigvee", "latex": "\\bigvee", "mathml": "&bigvee;"},
    {"asciimath": "nn", "latex": "\\cap", "mathml": "&cap;"},
    {"asciimath": "cap", "latex": "\\cap", "mathml": "&cap;"},
    {"asciimath": "nnn", "latex": "\\bigcap", "mathml": "&bigcap;"},
    {"asciimath": "bigcap", "latex": "\\bigcap", "mathml": "&bigcap;"},
    {"asciimath": "uu", "latex": "\\cup", "mathml": "&cup;"},
    {"asciimath": "cup", "latex": "\\cup", "mathml": "&cup;"},
    {"asciimath": "uuu", "latex": "\\bigcup", "mathml": "&bigcup;"},
    {"asciimath": "bigcup", "latex": "\\bigcup", "mathml": "&bigcup;"},
]

logical_symbols = [
    {"asciimath": "and", "latex": "\\mathmr{and}", "mathml": "and"},
    {"asciimath": "or", "latex": "\\mathmr{and}", "mathml": "or"},
    {"asciimath": "not", "latex": "\\neg", "mathml": "&not;"},
    {"asciimath": "neg", "latex": "\\neg", "mathml": "&not;"},
    {"asciimath": "=>", "latex": "\\implies", "mathml": "&Implies;"},
    {"asciimath": "implies", "latex": "\\implies", "mathml": "&Implies;"},
    {"asciimath": "if", "latex": "\\mathmr{if}", "mathml": "if"},
    {"asciimath": "<=>", "latex": "\\iff", "mathml": "&iff;"},
    {"asciimath": "iff", "latex": "\\iff", "mathml": "&iff;"},
    {"asciimath": "AA", "latex": "\\forall", "mathml": "&ForAll;"},
    {"asciimath": "forall", "latex": "\\forall", "mathml": "&ForAll;"},
    {"asciimath": "EE", "latex": "\\exists", "mathml": "&Exists;"},
    {"asciimath": "exists", "latex": "\\exists", "mathml": "&Exists;"},
    {"asciimath": "_|_", "latex": "\\bot", "mathml": "&bot;"},
    {"asciimath": "bot", "latex": "\\bot", "mathml": "&bot;"},
    {"asciimath": "TT", "latex": "\\top", "mathml": "&top;"},
    {"asciimath": "top", "latex": "\\top", "mathml": "&top;"},
    {"asciimath": "|--", "latex": "\\vdash", "mathml": "&RightTee;"},
    {"asciimath": "vdash", "latex": "\\vdash", "mathml": "&RightTee;"},
    {"asciimath": "|==", "latex": "\\models", "mathml": "&DoubleRightTee;"},
    {
        "asciimath": "models",
        "latex": "\\models",
        "mathml": "&DoubleRightTee;",
    },
]

relation_symbols = [
    {"asciimath": "=", "latex": "=", "mathml": "="},
    {"asciimath": "!=", "latex": "\\ne", "mathml": "&NotEqual;"},
    {"asciimath": "ne", "latex": "\\ne", "mathml": "&NotEqual;"},
    {"asciimath": "<", "latex": "<", "mathml": "&lt;"},
    {"asciimath": "lt", "latex": "<", "mathml": "&lt;"},
    {"asciimath": ">", "latex": ">", "mathml": "&gt;"},
    {"asciimath": "gt", "latex": ">", "mathml": "&gt;"},
    {"asciimath": "<=", "latex": "\\le", "mathml": "&leq;"},
    {"asciimath": "le", "latex": "\\le", "mathml": "&leq;"},
    {"asciimath": ">=", "latex": "\\ge", "mathml": "&geq;"},
    {"asciimath": "ge", "latex": "\\ge", "mathml": "&geq;"},
    {"asciimath": "-<", "latex": "\\prec", "mathml": "&Precedes;"},
    {"asciimath": "prec", "latex": "\\prec", "mathml": "&Precedes;"},
    {"asciimath": "-<=", "latex": "\\preceq", "mathml": "&PrecedesEqual;"},
    {"asciimath": "preceq", "latex": "\\preceq", "mathml": "&PrecedesEqual;"},
    {"asciimath": ">-", "latex": "\\succ", "mathml": "&Succeeds;"},
    {"asciimath": "succ", "latex": "\\succ", "mathml": "&Succeeds;"},
    {"asciimath": ">-=", "latex": "\\succeq", "mathml": "&SucceedsEqual;"},
    {"asciimath": "succeq", "latex": "\\succeq", "mathml": "&SucceedsEqual;"},
    {"asciimath": "in", "latex": "\\in", "mathml": "&in;"},
    {"asciimath": "!in", "latex": "\\notin", "mathml": "&notin;"},
    {"asciimath": "notin", "latex": "\\notin", "mathml": "&notin;"},
    {"asciimath": "sub", "latex": "\\subset", "mathml": "&subset;"},
    {"asciimath": "subset", "latex": "\\subset", "mathml": "&subset;"},
    {"asciimath": "sup", "latex": "\\supset", "mathml": "&supset;"},
    {"asciimath": "supset", "latex": "\\supset", "mathml": "&supset;"},
    {"asciimath": "sube", "latex": "\\subseteq", "mathml": "&SubsetEqual;"},
    {
        "asciimath": "subseteq",
        "latex": "\\subseteq",
        "mathml": "&SubsetEqual;",
    },
    {"asciimath": "supe", "latex": "\\supseteq", "mathml": "&SupersetEqual;"},
    {
        "asciimath": "supseteq",
        "latex": "\\supseteq",
        "mathml": "&SupersetEqual;",
    },
    {"asciimath": "-=", "latex": "\\equiv", "mathml": "&equiv;"},
    {"asciimath": "equiv", "latex": "\\equiv", "mathml": "&equiv;"},
    {"asciimath": "~=", "latex": "\\cong", "mathml": "&cong;"},
    {"asciimath": "cong", "latex": "\\cong", "mathml": "&cong;"},
    {"asciimath": "~~", "latex": "\\approx", "mathml": "&approx;"},
    {"asciimath": "approx", "latex": "\\approx", "mathml": "&approx;"},
    {"asciimath": "prop", "latex": "\\propto", "mathml": "&prop;"},
    {"asciimath": "propto", "latex": "\\propto", "mathml": "&prop;"},
]

function_symbols = [
    {"asciimath": "sin", "latex": "\\sin", "mathml": "sin"},
    {"asciimath": "cos", "latex": "\\cos", "mathml": "cos"},
    {"asciimath": "tan", "latex": "\\tan", "mathml": "tan"},
    {"asciimath": "sec", "latex": "\\sec", "mathml": "sec"},
    {"asciimath": "csc", "latex": "\\csc", "mathml": "csc"},
    {"asciimath": "cot", "latex": "\\cot", "mathml": "cot"},
    {"asciimath": "arcsin", "latex": "\\arcsin", "mathml": "arcsin"},
    {"asciimath": "arccos", "latex": "\\arccos", "mathml": "arccos"},
    {"asciimath": "arctan", "latex": "\\arctan", "mathml": "arctan"},
    {"asciimath": "sinh", "latex": "\\sinh", "mathml": "sinh"},
    {"asciimath": "cosh", "latex": "\\cosh", "mathml": "cosh"},
    {"asciimath": "tanh", "latex": "\\tanh", "mathml": "tanh"},
    {"asciimath": "sech", "latex": "\\sech", "mathml": "sech"},
    {"asciimath": "csch", "latex": "\\csch", "mathml": "csch"},
    {"asciimath": "coth", "latex": "\\coth", "mathml": "coth"},
    {"asciimath": "exp", "latex": "\\exp", "mathml": "exp"},
    {"asciimath": "log", "latex": "\\log", "mathml": "log"},
    {"asciimath": "ln", "latex": "\\ln", "mathml": "ln"},
    {"asciimath": "det", "latex": "\\det", "mathml": "det"},
    {"asciimath": "dim", "latex": "\\dim", "mathml": "dim"},
    {"asciimath": "mod", "latex": "\\mod", "mathml": "mod"},
    {"asciimath": "gcd", "latex": "\\gcd", "mathml": "gcd"},
    {"asciimath": "lcm", "latex": "\\lcm", "mathml": "lcm"},
    {"asciimath": "lub", "latex": "\\lub", "mathml": "lub"},
    {"asciimath": "glb", "latex": "\\glb", "mathml": "glb"},
    {"asciimath": "min", "latex": "\\min", "mathml": "min"},
    {"asciimath": "max", "latex": "\\max", "mathml": "max"},
    {"asciimath": "lim", "latex": "\\lim", "mathml": "lim"},
    {"asciimath": "f", "latex": "f", "mathml": "f"},
    {"asciimath": "g", "latex": "g", "mathml": "g"},
]

greek_letters = [
    {"asciimath": "alpha", "latex": "\\alpha", "mathml": "&alpha;"},
    {"asciimath": "beta", "latex": "\\beta", "mathml": "&beta;"},
    {"asciimath": "gamma", "latex": "\\gamma", "mathml": "&gamma;"},
    {"asciimath": "Gamma", "latex": "\\Gamma", "mathml": "&Gamma;"},
    {"asciimath": "delta", "latex": "\\delta", "mathml": "&delta;"},
    {"asciimath": "Delta", "latex": "\\Delta", "mathml": "&Delta;"},
    {"asciimath": "epsilon", "latex": "\\epsilon", "mathml": "&epsiv;"},
    {
        "asciimath": "varepsilon",
        "latex": "\\varepsilon",
        "mathml": "&varepsilon;",
    },
    {"asciimath": "zeta", "latex": "\\zeta", "mathml": "&zeta;"},
    {"asciimath": "eta", "latex": "\\eta", "mathml": "&eta;"},
    {"asciimath": "theta", "latex": "\\theta", "mathml": "&theta;"},
    {"asciimath": "Theta", "latex": "\\Theta", "mathml": "&Theta;"},
    {"asciimath": "vartheta", "latex": "\\vartheta", "mathml": "&vartheta;"},
    {"asciimath": "iota", "latex": "\\iota", "mathml": "&iota;"},
    {"asciimath": "kappa", "latex": "\\kappa", "mathml": "&kappa;"},
    {"asciimath": "lambda", "latex": "\\lambda", "mathml": "&lambda;"},
    {"asciimath": "Lambda", "latex": "\\Lambda", "mathml": "&Lambda;"},
    {"asciimath": "mu", "latex": "\\mu", "mathml": "&mu;"},
    {"asciimath": "nu", "latex": "\\nu", "mathml": "&nu;"},
    {"asciimath": "xi", "latex": "\\xi", "mathml": "&xi;"},
    {"asciimath": "Xi", "latex": "\\Xi", "mathml": "&Xi;"},
    {"asciimath": "pi", "latex": "\\pi", "mathml": "&pi;"},
    {"asciimath": "Pi", "latex": "\\Pi", "mathml": "&Pi;"},
    {"asciimath": "rho", "latex": "\\rho", "mathml": "&rho;"},
    {"asciimath": "sigma", "latex": "\\sigma", "mathml": "&sigma;"},
    {"asciimath": "Sigma", "latex": "\\Sigma", "mathml": "&Sigma;"},
    {"asciimath": "tau", "latex": "\\tau", "mathml": "&tau;"},
    {"asciimath": "upsilon", "latex": "\\upsilon", "mathml": "&upsilon;"},
    {"asciimath": "phi", "latex": "\\phi", "mathml": "&phi;"},
    {"asciimath": "Phi", "latex": "\\Phi", "mathml": "&Phi;"},
    {"asciimath": "varphi", "latex": "\\varphi", "mathml": "&varphi;"},
    {"asciimath": "chi", "latex": "\\chi", "mathml": "&chi;"},
    {"asciimath": "psi", "latex": "\\psi", "mathml": "&psi;"},
    {"asciimath": "Psi", "latex": "\\Psi", "mathml": "&Psi;"},
    {"asciimath": "omega", "latex": "\\omega", "mathml": "&omega;"},
    {"asciimath": "Omega", "latex": "\\Omega", "mathml": "&Omega;"},
]

left_parenthesis = [
    {"asciimath": "(:", "latex": "\\langle", "mathml": "&langle;"},
    {"asciimath": "(", "latex": "(", "mathml": "("},
    {"asciimath": "[", "latex": "[", "mathml": "["},
    {"asciimath": "{:", "latex": ".", "mathml": ""},
    {"asciimath": "{", "latex": "\\{", "mathml": "{"},
    {"asciimath": "|:", "latex": "\\vert", "mathml": "&VerticalBar;"},
    {"asciimath": "||:", "latex": "\\lVert", "mathml": "&DoubleVerticalBar;"},
    {"asciimath": "langle", "latex": "\\langle", "mathml": "&langle;"},
    {"asciimath": "<<", "latex": "\\langle", "mathml": "&langle;"},
]

right_parenthesis = [
    {"asciimath": ":)", "latex": "\\rangle", "mathml": "&rangle;"},
    {"asciimath": ")", "latex": ")", "mathml": ")"},
    {"asciimath": "]", "latex": "]", "mathml": "]"},
    {"asciimath": ":}", "latex": ".", "mathml": ""},
    {"asciimath": "}", "latex": "\\}", "mathml": "}"},
    {"asciimath": ":|", "latex": "\\vert", "mathml": "&VerticalBar;"},
    {"asciimath": ":||", "latex": "\\rVert", "mathml": "&DoubleVerticalBar;"},
    {"asciimath": "rangle", "latex": "\\rangle", "mathml": "&rangle;"},
    {"asciimath": ">>", "latex": "\\rangle", "mathml": "&rangle;"},
]

arrows = [
    {"asciimath": "uarr", "latex": "\\uparrow", "mathml": "&uarr;"},
    {"asciimath": "uparrow", "latex": "\\uparrow", "mathml": "&uparrow;"},
    {"asciimath": "darr", "latex": "\\downarrow", "mathml": "&darr;"},
    {
        "asciimath": "downarrow",
        "latex": "\\downarrow",
        "mathml": "&downarrow;",
    },
    {"asciimath": "rarr", "latex": "\\rightarrow", "mathml": "&rarr;"},
    {"asciimath": "rArr", "latex": "\\Rightarrow", "mathml": "&rArr;"},
    {
        "asciimath": "rightarrow",
        "latex": "\\rightarrow",
        "mathml": "&rightarrow;",
    },
    {"asciimath": "->", "latex": "\\to", "mathml": "&rightarrow;"},
    {"asciimath": "to", "latex": "\\to", "mathml": "&rightarrow;"},
    {"asciimath": ">->", "latex": "\\rightarrowtail", "mathml": ""},
    {
        "asciimath": "rightarrowtail",
        "latex": "\\rightarrowtail",
        "mathml": "&rightarrowtail;",
    },
    {"asciimath": "->>", "latex": "\\twoheadrightarrow", "mathml": ""},
    {
        "asciimath": "twoheadrightarrow",
        "latex": "\\twoheadrightarrow",
        "mathml": "&twoheadrightarrow;",
    },
    {"asciimath": ">->>", "latex": "\\twoheadrightarrowtail", "mathml": ""},
    {
        "asciimath": "twoheadrightarrowtail",
        "latex": "\\twoheadrightarrowtail",
        "mathml": "&Rarrtl;",
    },
    {"asciimath": "|->", "latex": "\\mapsto", "mathml": ""},
    {"asciimath": "mapsto", "latex": "\\mapsto", "mathml": "&mapsto;"},
    {"asciimath": "larr", "latex": "\\leftarrow", "mathml": "&larr;"},
    {
        "asciimath": "leftarrow",
        "latex": "\\leftarrow",
        "mathml": "&leftarrow;",
    },
    {"asciimath": "harr", "latex": "\\leftrightarrow", "mathml": "&harr;"},
    {
        "asciimath": "leftrightarrow",
        "latex": "\\leftrightarrow",
        "mathml": "&leftrightarrow;",
    },
    {"asciimath": "lArr", "latex": "\\Leftarrow", "mathml": "&lArr;"},
    {
        "asciimath": "Leftarrow",
        "latex": "\\Leftarrow",
        "mathml": "&Leftarrow;",
    },
    {"asciimath": "hArr", "latex": "\\Leftrightarrow", "mathml": "&hArr;"},
    {
        "asciimath": "Leftrightarrow",
        "latex": "\\Leftrightarrow",
        "mathml": "&Leftrightarrow;",
    },
]

colors = [
    {"asciimath": "red", "latex": "red", "mathml": "red"},
]

misc_symbols = [
    {"asciimath": "^", "latex": "^", "mathml": "&#x5E;"},
    {"asciimath": ",", "latex": ",", "mathml": ","},
    {"asciimath": ".", "latex": ".", "mathml": "."},
    {"asciimath": "_", "latex": "_", "mathml": "_"},
    {"asciimath": "'", "latex": "'", "mathml": "'"},
    {"asciimath": "/", "latex": "/", "mathml": "/"},
    {"asciimath": "|", "latex": "|", "mathml": "|"},
    {"asciimath": ":", "latex": ":", "mathml": ":"},
    {"asciimath": "int", "latex": "\\int", "mathml": "&Integral;"},
    {"asciimath": "integral", "latex": "\\int", "mathml": "&Integral;"},
    {"asciimath": "oint", "latex": "\\oint", "mathml": "&conint;"},
    {"asciimath": "del", "latex": "\\partial", "mathml": "&part;"},
    {"asciimath": "partial", "latex": "\\partial", "mathml": "&part;"},
    {"asciimath": "grad", "latex": "\\nabla", "mathml": "&Del;"},
    {"asciimath": "nabla", "latex": "\\nabla", "mathml": "&Del;"},
    {"asciimath": "+-", "latex": "\\pm", "mathml": "&PlusMinus;"},
    {"asciimath": "pm", "latex": "\\pm", "mathml": "&PlusMinus;"},
    {"asciimath": "O/", "latex": "\\emptyset", "mathml": "&emptyset;"},
    {"asciimath": "emptyset", "latex": "\\emptyset", "mathml": "&emptyset;"},
    {"asciimath": "oo", "latex": "\\infty", "mathml": "&infin;"},
    {"asciimath": "infty", "latex": "\\infty", "mathml": "&infin;"},
    {"asciimath": "aleph", "latex": "\\aleph", "mathml": "&aleph;"},
    {"asciimath": ":.", "latex": "\\therefore", "mathml": "&therefore;"},
    {
        "asciimath": "therefore",
        "latex": "\\therefore",
        "mathml": "&therefore;",
    },
    {"asciimath": ":'", "latex": "\\because", "mathml": "&because;"},
    {"asciimath": "because", "latex": "\\because", "mathml": "&because;"},
    {"asciimath": "...", "latex": "\\ldots", "mathml": "..."},
    {"asciimath": "ldots", "latex": "\\ldots", "mathml": "..."},
    {"asciimath": "cdots", "latex": "\\cdots", "mathml": "&ctdot;"},
    {"asciimath": "vdots", "latex": "\\vdots", "mathml": "&vellip;"},
    {"asciimath": "ddots", "latex": "\\ddots", "mathml": "&dtdot;"},
    {"asciimath": "quad", "latex": "\\quad", "mathml": "&nbsp;"},
    {"asciimath": "/_", "latex": "\\angle", "mathml": "&angle;"},
    {"asciimath": "angle", "latex": "\\angle", "mathml": "&angle;"},
    {"asciimath": "frown", "latex": "\\frown", "mathml": "&frown;"},
    {
        "asciimath": r"/_\\",
        "latex": "\\triangle",
        "mathml": "&bigtriangleup;",
    },
    {
        "asciimath": "triangle",
        "latex": "\\triangle",
        "mathml": "&bigtriangleup;",
    },
    {"asciimath": "diamond", "latex": "\\diamond", "mathml": "&diamond;"},
    {"asciimath": "square", "latex": "\\square", "mathml": "&square;"},
    {"asciimath": "|__", "latex": "\\lfloor", "mathml": "&lfloor;"},
    {"asciimath": "lfloor", "latex": "\\lfloor", "mathml": "&lfloor;"},
    {"asciimath": "__|", "latex": "\\rfloor", "mathml": "&rfloor;"},
    {"asciimath": "rfloor", "latex": "\\rfloor", "mathml": "&rfloor;"},
    {"asciimath": "|~", "latex": "\\lceiling", "mathml": "&lceil;"},
    {"asciimath": "lceiling", "latex": "\\lceiling", "mathml": "&lceil;"},
    {"asciimath": "~|", "latex": "\\rceiling", "mathml": "&rceil;"},
    {"asciimath": "rceiling", "latex": "\\rceiling", "mathml": "&rceil;"},
    {"asciimath": "CC", "latex": "\\mathbb{C}", "mathml": "&Copf;"},
    {"asciimath": "NN", "latex": "\\mathbb{N}", "mathml": "&Nopf;"},
    {"asciimath": "QQ", "latex": "\\mathbb{Q}", "mathml": "&Qopf;"},
    {"asciimath": "RR", "latex": "\\mathbb{R}", "mathml": "&Ropf;"},
    {"asciimath": "ZZ", "latex": "\\mathbb{Z}", "mathml": "&Zopf;"},
]

# matrix2par = {
#     "pmatrix": ["(", ")"],
#     "bmatrix": ["[", "]"],
#     "Bmatrix": ["\{", "\}"],
#     "vmatrix": ["|", "|"],
#     "Vmatrix": ["||", "||"],
# }
